; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel @ ^1.12.3
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
	adafruit/Adafruit GFX Library @ ^1.11.9
	https://github.com/arozcan/MFRC522-I2C-Library.git
	h2zero/NimBLE-Arduino @ ^1.4.1

build_flags = 
	; NimBLE buffer tuning for connectionless passive scanning to prevent OOM
	-D CONFIG_NIMBLE_MAX_CONNECTIONS=0
	-D CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=12
	-D CONFIG_BT_NIMBLE_MSYS2_BLOCK_COUNT=12
